import { Pool, type PoolClient } from 'pg';
import type { NormalizedRestaurantRecord } from './normalizer';

export class CanonicalUpsertPipeline {
  private readonly pool: Pool;
  constructor(connectionString = process.env.DATABASE_URL) { this.pool = new Pool({ connectionString, host: process.env.PGHOST ?? 'localhost', port: Number(process.env.PGPORT ?? 5432), database: process.env.PGDATABASE ?? 'food_app', user: process.env.PGUSER ?? 'food_app', password: process.env.PGPASSWORD ?? 'change-me-locally' }); }
  async close() { await this.pool.end(); }
  async ensureLocalFixtureSource(): Promise<void> {
    if (process.env.CRAWL_FIXTURE_LOCAL !== 'true') throw new Error('Fixture ingestion is disabled by default. Set CRAWL_FIXTURE_LOCAL=true for local-only test data.');
    await this.pool.query(`INSERT INTO data_source (code, name, base_url, is_active) VALUES ('fixture', 'Local Fixture (test only)', 'https://example.test/fixture', true) ON CONFLICT (code) DO UPDATE SET is_active = true`);
  }
  async hasCompletedRun(providerCode: string, query: string, location: string): Promise<boolean> { const result = await this.pool.query<{ exists: boolean }>(`SELECT EXISTS(SELECT 1 FROM crawl_run cr JOIN data_source ds ON ds.id = cr.data_source_id WHERE ds.code = $1 AND cr.status = 'completed' AND cr.target->>'query' = $2 AND cr.target->>'location' = $3)`, [providerCode, query, location]); return result.rows[0]?.exists ?? false; }
  async createCrawlRun(providerCode: string, target: Record<string, unknown>) { const result = await this.pool.query<{ id: string }>(`INSERT INTO crawl_run (data_source_id, job_type, target, status, started_at) SELECT id, 'discovery', $2::jsonb, 'running', now() FROM data_source WHERE code = $1 AND is_active = true RETURNING id`, [providerCode, JSON.stringify(target)]); if (!result.rows[0]) throw new Error(`Active data source '${providerCode}' was not found.`); return result.rows[0].id; }
  async process(crawlRunId: string, record: NormalizedRestaurantRecord): Promise<string> {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN'); const source = await client.query<{ id: string; restaurant_id: string }>('SELECT rs.id, rs.restaurant_id FROM restaurant_source rs JOIN data_source ds ON ds.id = rs.data_source_id WHERE ds.code = $1 AND rs.external_id = $2 FOR UPDATE', [record.providerCode, record.externalId]); let restaurantId = source.rows[0]?.restaurant_id;
      if (!restaurantId) {
        const candidate = record.coordinates
          ? await client.query<{ id: string }>(`SELECT r.id FROM restaurant r JOIN location l ON l.id = r.location_id WHERE r.status <> 'permanently_closed' AND r.normalized_name = $1 AND l.coordinates IS NOT NULL AND ST_DWithin(l.coordinates, ST_SetSRID(ST_MakePoint($2, $3), 4326)::geography, 150) LIMIT 1`, [record.normalizedName, record.coordinates.longitude, record.coordinates.latitude])
          : await client.query<{ id: string }>(`SELECT r.id FROM restaurant r JOIN location l ON l.id = r.location_id WHERE r.status <> 'permanently_closed' AND r.normalized_name = $1 AND ($2::text IS NULL OR lower(l.formatted_address) = lower($2)) AND ($3::text IS NULL OR lower(l.city) = lower($3)) LIMIT 1`, [record.normalizedName, record.formattedAddress ?? null, record.city ?? null]);
        restaurantId = candidate.rows[0]?.id;
      }
      if (!restaurantId) { const location = await client.query<{ id: string }>(`INSERT INTO location (address_line, district, city, country_code, formatted_address, coordinates) VALUES ($1,$2,$3,$4,$5,CASE WHEN $6::double precision IS NULL THEN NULL ELSE ST_SetSRID(ST_MakePoint($6,$7),4326)::geography END) RETURNING id`, [record.address ?? null, record.district ?? null, record.city ?? null, record.countryCode ?? null, record.formattedAddress, record.coordinates?.longitude ?? null, record.coordinates?.latitude ?? null]); const restaurant = await client.query<{ id: string }>(`INSERT INTO restaurant (name, normalized_name, description, location_id, phone, website_url, price_level, rating, review_count, status) VALUES ($1,$2,NULL,$3,$4,$5,$6,$7,$8,'active') RETURNING id`, [record.name, record.normalizedName, location.rows[0].id, record.phone ?? null, record.websiteUrl ?? null, record.priceLevel ?? null, record.rating ?? null, record.reviewCount ?? null]); restaurantId = restaurant.rows[0].id; }
      const sourceResult = await client.query<{ id: string }>(`INSERT INTO restaurant_source (restaurant_id, data_source_id, external_id, source_url, source_name, source_rating, source_review_count, raw_data, last_seen_at, status) SELECT $1, ds.id, $2, $3, $4, $5, $6, $7::jsonb, $8, 'active' FROM data_source ds WHERE ds.code = $9 ON CONFLICT (data_source_id, external_id) DO UPDATE SET restaurant_id = EXCLUDED.restaurant_id, source_url = EXCLUDED.source_url, source_name = EXCLUDED.source_name, source_rating = EXCLUDED.source_rating, source_review_count = EXCLUDED.source_review_count, raw_data = EXCLUDED.raw_data, last_seen_at = EXCLUDED.last_seen_at, status = 'active' RETURNING id`, [restaurantId, record.externalId, record.sourceUrl ?? null, record.name, record.rating ?? null, record.reviewCount ?? null, JSON.stringify(record.sourceMetadata), record.collectedAt, record.providerCode]); const sourceId = sourceResult.rows[0].id;
      await client.query(`UPDATE restaurant SET name = COALESCE(NULLIF($2,''), name), normalized_name = COALESCE(NULLIF($3,''), normalized_name), phone = COALESCE($4, phone), website_url = COALESCE($5, website_url), price_level = COALESCE($6, price_level), rating = COALESCE($7, rating), review_count = CASE WHEN $8::integer IS NULL THEN review_count ELSE $8 END, updated_at = now() WHERE id = $1`, [restaurantId, record.name, record.normalizedName, record.phone ?? null, record.websiteUrl ?? null, record.priceLevel ?? null, record.rating ?? null, record.reviewCount ?? null]);
      for (const slug of record.categories ?? []) { await client.query(`INSERT INTO restaurant_category (restaurant_id, category_id, source, confidence) SELECT $1, id, $3, 1 FROM category WHERE slug = $2 AND is_active = true ON CONFLICT (restaurant_id, category_id) DO UPDATE SET source = EXCLUDED.source, confidence = EXCLUDED.confidence`, [restaurantId, slug, record.providerCode]); }
      for (const image of record.images ?? []) await client.query(`INSERT INTO restaurant_image (restaurant_id, restaurant_source_id, url, alt_text, sort_order, is_cover, status) VALUES ($1,$2,$3,$4,$5,$6,'active') ON CONFLICT DO NOTHING`, [restaurantId, sourceId, image.url, image.altText ?? null, image.sortOrder ?? 0, image.isCover ?? false]);
      for (const dish of record.dishes ?? []) await client.query(`INSERT INTO dish (restaurant_id, name, normalized_name, description, price_amount, currency_code, is_popular, status) SELECT $1,$2,$3,$4,$5,$6,$7,'available' WHERE NOT EXISTS (SELECT 1 FROM dish WHERE restaurant_id = $1 AND normalized_name = $3)`, [restaurantId, dish.name.trim(), dish.name.trim().toLowerCase(), dish.description ?? null, dish.priceAmount ?? null, dish.currencyCode ?? null, dish.isPopular ?? false]);
      for (const hour of record.openingHours ?? []) await client.query(`INSERT INTO restaurant_hour (restaurant_id, day_of_week, opens_at, closes_at, is_closed, spans_next_day) SELECT $1,$2,$3,$4,$5,$6 WHERE NOT EXISTS (SELECT 1 FROM restaurant_hour WHERE restaurant_id=$1 AND day_of_week=$2 AND opens_at IS NOT DISTINCT FROM $3::time AND closes_at IS NOT DISTINCT FROM $4::time)`, [restaurantId, hour.dayOfWeek, hour.opensAt, hour.closesAt, hour.isClosed, hour.spansNextDay ?? false]);
      for (const review of record.reviews ?? []) {
        await client.query(`INSERT INTO review (restaurant_id, restaurant_source_id, external_review_id, rating, content, reviewed_at, language_code, is_visible) VALUES ($1,$2,$3,$4,$5,$6,$7,true) ON CONFLICT (restaurant_source_id, external_review_id) DO UPDATE SET rating = EXCLUDED.rating, content = EXCLUDED.content, reviewed_at = EXCLUDED.reviewed_at, language_code = EXCLUDED.language_code, is_visible = true`, [restaurantId, sourceId, review.externalReviewId, review.rating ?? null, review.content ?? null, review.reviewedAt ?? null, review.languageCode ?? null]);
      }
      await client.query(`INSERT INTO processing_record (crawl_run_id, restaurant_source_id, external_id, stage, status, attempt_count, processed_at) VALUES ($1,$2,$3,'normalization','completed',1,now()) ON CONFLICT (crawl_run_id, COALESCE(restaurant_source_id, '00000000-0000-0000-0000-000000000000'::uuid), COALESCE(external_id, ''), stage) DO UPDATE SET restaurant_source_id = EXCLUDED.restaurant_source_id, external_id = EXCLUDED.external_id, status = 'completed', attempt_count = processing_record.attempt_count + 1, error_details = NULL, processed_at = now()`, [crawlRunId, sourceId, record.externalId]); await client.query('COMMIT'); return restaurantId;
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async recordFailure(crawlRunId: string, externalId: string | undefined, stage: 'validation' | 'normalization', error: unknown): Promise<void> {
    const message = error instanceof Error ? error.message : 'Unknown record failure.';
    await this.pool.query(`INSERT INTO processing_record (crawl_run_id, external_id, stage, status, attempt_count, error_details, processed_at) VALUES ($1, $2, $3, 'failed', 1, $4::jsonb, now()) ON CONFLICT (crawl_run_id, COALESCE(restaurant_source_id, '00000000-0000-0000-0000-000000000000'::uuid), COALESCE(external_id, ''), stage) DO UPDATE SET status = 'failed', attempt_count = processing_record.attempt_count + 1, error_details = EXCLUDED.error_details, processed_at = now()`, [crawlRunId, externalId ?? null, stage, JSON.stringify({ message })]);
  }
  async finishCrawlRun(crawlRunId: string, found: number, processed: number) { await this.pool.query(`UPDATE crawl_run SET status='completed', finished_at=now(), worker_id=NULL, lease_expires_at=NULL, records_found=$2, records_processed=$3 WHERE id=$1`, [crawlRunId, found, processed]); }
  async failCrawlRun(crawlRunId: string, found: number, processed: number, error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown crawl failure.';
    await this.pool.query(`UPDATE crawl_run SET status='failed', finished_at=now(), worker_id=NULL, lease_expires_at=NULL, records_found=$2, records_processed=$3, error_message=$4 WHERE id=$1`, [crawlRunId, found, processed, message]);
  }
}
